# -*- coding: utf-8 -*-
"""Job Market Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTeo6Y-90P7gl0K051bGC-K4AAkvhUv-

### 1. DESCRIPTION

**Data Science Job Market Analysis in Indonesia**

Source: Jobstreet Indonesia (https://id.jobstreet.com)

Scraped using: Selenium + BeautifulSoup

---

Target: Analyze the Data Science job market in Indonesia
- What roles are most in demand?
- What skills are required?
- Where are the jobs located?
- What industries are hiring?

Workflow:
1. Web Scraping (Selenium + BeautifulSoup)
2. Data Cleaning
3. Store to SQLite Database
4. SQL Analysis
5. Exploratory Data Analysis (EDA)
6. Skill Demand Analysis
7. Conclusion

### 2. INSTALL & IMPORT LIBRARIES

**Step 1: Install all dependencies (run once di Colab)**
"""

import subprocess, sys

subprocess.run(["pip", "install", "-q",
                "selenium", "beautifulsoup4", "lxml",
                "wordcloud", "webdriver-manager"], check=True)

result = subprocess.run(
    ["bash", "-c",
     "wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb "
     "&& apt-get install -y ./google-chrome-stable_current_amd64.deb -qq "
     "&& rm google-chrome-stable_current_amd64.deb"],
    capture_output=True, text=True
)
if result.returncode == 0:
    print("✅ Google Chrome installed.")
else:
    print("⚠️ Chrome install output:", result.stderr[-300:])

# Verify Chrome version
ver = subprocess.run(["google-chrome", "--version"],
                     capture_output=True, text=True).stdout.strip()
print(f"   Chrome version : {ver}")

"""**Step 2: Imports**"""

import re
import time
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from wordcloud import WordCloud

from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.os_manager import ChromeType

import os
os.makedirs('images', exist_ok=True)

"""### 3. WEB SCRAPING — JOBSTREET INDONESIA

**Helper: Setup Selenium Driver**
"""

def get_driver():
    """
    Setup Chrome driver for Google Colab.
    Uses Google Chrome stable + webdriver-manager that automatically fit the ChromeDriver version.
    """
    options = Options()
    options.add_argument("--headless=new")          # headless mode terbaru
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1920,1080")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--disable-extensions")
    options.add_argument("--proxy-server='direct://'")
    options.add_argument("--proxy-bypass-list=*")
    options.add_argument("--ignore-certificate-errors")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)
    options.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )

    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    driver.execute_script(
        "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
    )
    return driver

"""**Helper: Parse One Page of Job Cards**"""

def parse_jobs(soup):
    jobs = []
    cards = soup.find_all('article', attrs={'data-card-type': 'JobCard'})

    for card in cards:
        title_tag    = card.find('a',    attrs={'data-automation': 'jobTitle'})
        company_tag  = card.find('a',    attrs={'data-automation': 'jobCompany'})
        location_tag = card.find('span', attrs={'data-automation': 'jobCardLocation'})
        salary_tag   = card.find('span', attrs={'data-automation': 'jobSalary'})
        jobtype_tag  = card.find('span', attrs={'data-automation': 'jobWorkType'})
        date_tag     = card.find('span', attrs={'data-automation': 'jobListingDate'})
        desc_tag     = card.find('div',  attrs={'data-automation': 'jobShortDescription'})
        link_tag     = card.find('a',    attrs={'data-automation': 'jobTitle'})

        job_url = ('https://id.jobstreet.com' + link_tag['href']
                   if link_tag and link_tag.get('href') else None)

        jobs.append({
            'title':        title_tag.get_text(strip=True)    if title_tag    else None,
            'company':      company_tag.get_text(strip=True)  if company_tag  else None,
            'location':     location_tag.get_text(strip=True) if location_tag else None,
            'salary':       salary_tag.get_text(strip=True)   if salary_tag   else None,
            'job_type':     jobtype_tag.get_text(strip=True)  if jobtype_tag  else None,
            'date_listed':  date_tag.get_text(strip=True)     if date_tag     else None,
            'description':  desc_tag.get_text(strip=True)     if desc_tag     else None,
            'url':          job_url
        })
    return jobs

"""**Helper: Fetch Full Description from Job Detail Page**"""

def fetch_full_description(driver, url, timeout=8):
    """
    Visit individual job page and extract full job description text.
    Returns empty string if failed or timed out.
    """
    if not url:
        return ''
    try:
        driver.get(url)
        WebDriverWait(driver, timeout).until(
            EC.presence_of_element_located(
                (By.CSS_SELECTOR,
                 "[data-automation='jobAdDetails'], "
                 "[data-automation='job-detail-page'], "
                 ".job-detail, #job-description")
            )
        )
        time.sleep(1)
        soup = BeautifulSoup(driver.page_source, 'lxml')

        # Try multiple selectors Jobstreet uses for full description
        for selector in [
            {'data-automation': 'jobAdDetails'},
            {'data-automation': 'job-detail-page'},
            {'class': 'job-detail'},
        ]:
            tag = soup.find(attrs=selector)
            if tag:
                return tag.get_text(separator=' ', strip=True)

        # Fallback: get all text from main content area
        main = soup.find('main') or soup.find('article')
        return main.get_text(separator=' ', strip=True) if main else ''

    except Exception:
        return ''  # silently skip if page fails

"""**Helper: Scrape Full Description from Job Detail Page**"""

def scrape_job_detail(driver, url, timeout=8):
    """
    Visit individual job page and extract full job description.
    Returns full text or None if failed.
    """
    if not url:
        return None
    try:
        driver.get(url)
        WebDriverWait(driver, timeout).until(
            EC.presence_of_element_located(
                (By.CSS_SELECTOR, "[data-automation='jobAdDetails']")
            )
        )
        time.sleep(1)
        soup = BeautifulSoup(driver.page_source, 'lxml')
        # Primary selector for full job description
        detail = soup.find(attrs={'data-automation': 'jobAdDetails'})
        if detail:
            return detail.get_text(separator=' ', strip=True)
        # Fallback selectors
        for sel in ['job-detail-content', 'job-description', 'jobDescription']:
            el = soup.find(class_=sel) or soup.find(id=sel)
            if el:
                return el.get_text(separator=' ', strip=True)
    except Exception:
        pass
    return None

"""**Main Scraper**"""

def scrape_jobstreet(keywords, max_pages=5, scrape_detail=True, detail_limit=50):
    """
    Scrape Jobstreet Indonesia for multiple job keywords.

    Parameters
    ----------
    keywords : list of str
        e.g. ['data scientist', 'data analyst', 'data engineer', 'machine learning']
    max_pages : int
        Maximum pages per keyword (1 page ≈ 30 jobs)
    scrape_detail : bool
        If True, visit each job page to get full description (slower but richer)
    detail_limit : int
        Max number of detail pages to scrape per keyword (to save time)

    Returns
    -------
    pd.DataFrame
    """
    all_jobs = []
    driver = get_driver()

    for keyword in keywords:
        print(f"\n🔍 Scraping: '{keyword}'")
        keyword_slug = keyword.lower().replace(' ', '-')
        detail_count = 0

        for page in range(1, max_pages + 1):
            url = (f"https://id.jobstreet.com/{keyword_slug}-jobs"
                   f"?page={page}&sortmode=ListedDate")
            print(f"   Page {page}: {url}")

            try:
                driver.get(url)
                WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "article[data-card-type='JobCard']")
                    )
                )
                time.sleep(2)

                soup  = BeautifulSoup(driver.page_source, 'lxml')
                jobs  = parse_jobs(soup)

                if not jobs:
                    print(f"   ⚠️  No jobs found on page {page}, stopping.")
                    break

                # Scrape full description for each job
                if scrape_detail:
                    for job in jobs:
                        if detail_count < detail_limit and job.get('url'):
                            full_desc = scrape_job_detail(driver, job['url'])
                            if full_desc:
                                # Combine snippet + full desc for max coverage
                                job['description'] = (
                                    (job.get('description') or '') + ' ' + full_desc
                                ).strip()
                            detail_count += 1

                for job in jobs:
                    job['search_keyword'] = keyword

                all_jobs.extend(jobs)
                print(f"   ✅ {len(jobs)} jobs collected "
                      f"(detail scraped: {min(detail_count, len(jobs))})")

            except Exception as e:
                print(f"   ❌ Error on page {page}: {e}")
                break

    driver.quit()
    df = pd.DataFrame(all_jobs)
    print(f"\n✅ Total jobs scraped: {len(df)}")
    return df

"""**Run Scraper**"""

KEYWORDS = [
    'data scientist',
    'data analyst',
    'data engineer',
    'machine learning engineer',
    'business analyst',
    'data science'
]

import os
if os.path.exists('jobs_raw_full.csv'):
    # Load existing full-description if data already exist
    print("📂 Loading existing jobs_raw_full.csv ...")
    df_raw = pd.read_csv('jobs_raw_full.csv')
    print(f"✅ Loaded {len(df_raw)} rows from cache.")
else:
    df_raw = scrape_jobstreet(
        keywords=KEYWORDS,
        max_pages=5,
        scrape_detail=True,   # take full description from detail page
        detail_limit=50       # max 50 detail per keyword = max 300 total
    )
    df_raw.to_csv('jobs_raw_full.csv', index=False)
    print("Raw data saved to jobs_raw_full.csv")

df_raw.head()

"""### 4. DATA CLEANING"""

df = df_raw.copy()

# Drop duplicates based on title + company + location
df = df.drop_duplicates(subset=['title', 'company', 'location'])
df = df.reset_index(drop=True)

print(f"After deduplication: {len(df)} rows")

# Standardize location — extract city only
def extract_city(loc):
    if pd.isna(loc):
        return 'Unknown'
    loc = str(loc)
    # Take part before comma if exists
    city = loc.split(',')[0].strip()
    # Normalize common city name variations
    city = re.sub(r'(?i)^(south|selatan)\s+jakarta|jakarta\s+(south|selatan)', 'South Jakarta', city)
    city = re.sub(r'(?i)^(north|utara)\s+jakarta|jakarta\s+(north|utara)',     'North Jakarta', city)
    city = re.sub(r'(?i)^(west|barat)\s+jakarta|jakarta\s+(west|barat)',       'West Jakarta',  city)
    city = re.sub(r'(?i)^(east|timur)\s+jakarta|jakarta\s+(east|timur)',       'East Jakarta',  city)
    city = re.sub(r'(?i)^(central|pusat)\s+jakarta|jakarta\s+(central|pusat)', 'Central Jakarta', city)
    city = re.sub(r'(?i)jakarta.*', 'Jakarta', city)
    city = re.sub(r'(?i)bandung.*', 'Bandung', city)
    city = re.sub(r'(?i)surabaya.*', 'Surabaya', city)
    city = re.sub(r'(?i)yogyakarta.*', 'Yogyakarta', city)
    city = re.sub(r'(?i)tangerang.*', 'Tangerang', city)
    city = re.sub(r'(?i)bekasi.*', 'Bekasi', city)
    city = re.sub(r'(?i)depok.*', 'Depok', city)
    city = re.sub(r'(?i)bali.*', 'Bali', city)
    city = re.sub(r'(?i)semarang.*', 'Semarang', city)
    city = re.sub(r'(?i)medan.*', 'Medan', city)
    # Filter out "Indonesia" as city — it's a country, not a city
    if city.strip().lower() in ('indonesia', 'republic of indonesia', ''):
        return 'Unknown'
    return city

df['city'] = df['location'].apply(extract_city)

# Standardize job title into role category
def categorize_role(title):
    if pd.isna(title):
        return 'Other'
    t = title.lower()
    # Data Scientist
    if any(k in t for k in ['data scientist', 'data science', 'scientist data']):
        return 'Data Scientist'
    # ML / AI Engineer
    elif any(k in t for k in ['machine learning', 'ml engineer', 'ai engineer',
                               'deep learning', 'mlops', 'computer vision',
                               'nlp engineer', 'artificial intelligence']):
        return 'ML/AI Engineer'
    # Data Engineer
    elif any(k in t for k in ['data engineer', 'data pipeline', 'etl developer',
                               'data platform', 'data infrastructure',
                               'data warehouse', 'data architect']):
        return 'Data Engineer'
    # Data Analyst — broad matching
    elif any(k in t for k in ['data analyst', 'data analysis', 'analyst data',
                               'analytics engineer', 'reporting analyst',
                               'business data', 'insight analyst']):
        return 'Data Analyst'
    # Business Analyst / BI
    elif any(k in t for k in ['business analyst', 'business intelligence',
                               'bi analyst', 'bi developer', 'bi engineer',
                               'bi specialist', 'power bi', 'tableau developer',
                               'product analyst', 'system analyst',
                               'financial analyst', 'marketing analyst']):
        return 'Business Analyst/BI'
    # Data Manager / Lead
    elif any(k in t for k in ['data manager', 'head of data', 'chief data',
                               'data lead', 'director of data',
                               'vp of data', 'data governance']):
        return 'Data Manager/Lead'
    else:
        return 'Other Data Role'

df['role_category'] = df['title'].apply(categorize_role)

# Clean job_type — infer from title/description if selector returns empty
def infer_job_type(row):
    if pd.notna(row['job_type']) and row['job_type'] not in ('', 'Not specified'):
        return row['job_type']
    text = str(row.get('title', '')) + ' ' + str(row.get('description', ''))
    text = text.lower()
    if any(k in text for k in ['full time', 'full-time', 'permanent']):
        return 'Full Time'
    elif any(k in text for k in ['part time', 'part-time']):
        return 'Part Time'
    elif any(k in text for k in ['contract', 'freelance', 'project based']):
        return 'Contract'
    elif any(k in text for k in ['intern', 'magang', 'internship']):
        return 'Internship'
    else:
        return 'Not specified'

df['job_type'] = df.apply(infer_job_type, axis=1)

# Flag remote
df['is_remote'] = df['location'].str.contains(
    r'(?i)remote|wfh|work from home', na=False
)

# Save cleaned data
df.to_csv('jobs_cleaned.csv', index=False)
print(f"Cleaned data saved: {len(df)} rows, {df.shape[1]} columns")

df.head()

"""### 5. STORE TO SQLITE DATABASE"""

DB_PATH = 'job_market.db'
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# Create table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS jobs (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        title           TEXT,
        company         TEXT,
        location        TEXT,
        city            TEXT,
        salary          TEXT,
        job_type        TEXT,
        date_listed     TEXT,
        description     TEXT,
        url             TEXT,
        search_keyword  TEXT,
        role_category   TEXT,
        is_remote       INTEGER
    )
''')
conn.commit()

# Insert data
df_to_insert = df[[
    'title', 'company', 'location', 'city', 'salary',
    'job_type', 'date_listed', 'description', 'url',
    'search_keyword', 'role_category', 'is_remote'
]].copy()
df_to_insert['is_remote'] = df_to_insert['is_remote'].astype(int)
df_to_insert.to_sql('jobs', conn, if_exists='replace', index=False)

print(f"✅ {len(df_to_insert)} rows inserted into SQLite: '{DB_PATH}'")

"""### 6. SQL ANALYSIS"""

def run_query(sql, title=""):
    """Run SQL query and return DataFrame."""
    result = pd.read_sql_query(sql, conn)
    if title:
        print(f"\n{'='*55}")
        print(f"  {title}")
        print('='*55)
        print(result.to_string(index=False))
    return result

"""**Q1: Total jobs per role category**"""

q1 = run_query("""
    SELECT role_category,
           COUNT(*) AS total_jobs
    FROM jobs
    GROUP BY role_category
    ORDER BY total_jobs DESC
""", "Q1: Total Jobs per Role Category")

"""**Q2: Top 10 cities with most job postings**"""

q2 = run_query("""
    SELECT city,
           COUNT(*) AS total_jobs
    FROM jobs
    WHERE city != 'Unknown'
    GROUP BY city
    ORDER BY total_jobs DESC
    LIMIT 10
""", "Q2: Top 10 Cities")

"""**Q3: Job type distribution**"""

q3 = run_query("""
    SELECT job_type,
           COUNT(*) AS total
    FROM jobs
    GROUP BY job_type
    ORDER BY total DESC
""", "Q3: Job Type Distribution")

"""**Q4: Top 15 companies hiring most**"""

q4 = run_query("""
    SELECT company,
           COUNT(*) AS total_openings
    FROM jobs
    WHERE company IS NOT NULL
      AND company != 'Private Advertiser'
    GROUP BY company
    ORDER BY total_openings DESC
    LIMIT 15
""", "Q4: Top 15 Companies Hiring")

"""**Q5: Remote vs On-site**"""

q5 = run_query("""
    SELECT CASE WHEN is_remote = 1 THEN 'Remote' ELSE 'On-site' END AS work_type,
           COUNT(*) AS total
    FROM jobs
    GROUP BY is_remote
""", "Q5: Remote vs On-site")

"""**Q6: Role breakdown per city (top 5 cities)**"""

q6 = run_query("""
    SELECT city, role_category, COUNT(*) AS total
    FROM jobs
    WHERE city IN (
        SELECT city FROM jobs
        WHERE city != 'Unknown'
        GROUP BY city
        ORDER BY COUNT(*) DESC
        LIMIT 5
    )
    GROUP BY city, role_category
    ORDER BY city, total DESC
""", "Q6: Role Breakdown per Top 5 Cities")

"""**Q7: Jobs with salary info vs without**"""

q7 = run_query("""
    SELECT CASE WHEN salary IS NOT NULL AND salary != ''
                THEN 'Salary Listed'
                ELSE 'Salary Not Listed'
           END AS salary_status,
           COUNT(*) AS total,
           ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM jobs), 1) AS percentage
    FROM jobs
    GROUP BY salary_status
""", "Q7: Salary Transparency")

conn.close()

"""### 7. EXPLORATORY DATA ANALYSIS (EDA)"""

sns.set_theme(style='whitegrid')
COLORS = sns.color_palette('Blues_d', 10)

"""**Plot 1: Job Distribution by Role Category**"""

plt.figure(figsize=(9, 5))
role_counts = df['role_category'].value_counts()
sns.barplot(x=role_counts.values, y=role_counts.index,
            hue=role_counts.index, palette='Blues_d', legend=False)
plt.title("Job Distribution by Role Category", fontsize=14, fontweight='bold')
plt.xlabel("Number of Job Postings")
plt.ylabel("")
plt.tight_layout()
plt.savefig('images/role_distribution.png', dpi=150)
plt.show()

"""**Plot 2: Top 10 Cities**"""

plt.figure(figsize=(9, 5))
city_counts = df[df['city'] != 'Unknown']['city'].value_counts().head(10)
sns.barplot(x=city_counts.values, y=city_counts.index,
            hue=city_counts.index, palette='Blues_d', legend=False)
plt.title("Top 10 Cities with Most Data Job Postings", fontsize=14, fontweight='bold')
plt.xlabel("Number of Job Postings")
plt.ylabel("")
plt.tight_layout()
plt.savefig('images/top_cities.png', dpi=150)
plt.show()

"""**Plot 3: Job Type Distribution**"""

plt.figure(figsize=(7, 4))
jt_counts = df['job_type'].value_counts()
plt.pie(jt_counts.values, labels=jt_counts.index, autopct='%1.1f%%',
        colors=sns.color_palette('Blues', len(jt_counts)),
        startangle=140)
plt.title("Job Type Distribution", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('images/job_type_distribution.png', dpi=150)
plt.show()

"""**Plot 4: Remote vs On-site**"""

plt.figure(figsize=(6, 4))
remote_counts = df['is_remote'].map({True: 'Remote', False: 'On-site'}).value_counts()

remote_counts = remote_counts.reindex(['Remote', 'On-site'], fill_value=0)

n_categories  = (remote_counts > 0).sum()
full_palette   = ['#2196F3', '#90CAF9']
used_palette   = full_palette[:len(remote_counts)]

sns.barplot(x=remote_counts.index, y=remote_counts.values,
            hue=remote_counts.index, palette=used_palette, legend=False)
plt.title("Remote vs On-site Jobs", fontsize=13, fontweight='bold')
plt.ylabel("Number of Postings")
plt.xlabel("")
plt.tight_layout()
plt.savefig('images/remote_vs_onsite.png', dpi=150)
plt.show()

"""**Plot 5: Top 15 Companies Hiring**"""

plt.figure(figsize=(9, 6))
top_companies = (
    df[~df['company'].isin(['Private Advertiser', None])]
    ['company'].value_counts().head(15)
)
sns.barplot(x=top_companies.values, y=top_companies.index,
            hue=top_companies.index, palette='Blues_d', legend=False)
plt.title("Top 15 Companies Hiring Data Roles", fontsize=14, fontweight='bold')
plt.xlabel("Number of Openings")
plt.ylabel("")
plt.tight_layout()
plt.savefig('images/top_companies.png', dpi=150)
plt.show()

"""**Plot 6: Role Category per Top City (heatmap)**"""

top5_cities = df[df['city'] != 'Unknown']['city'].value_counts().head(5).index.tolist()
city_role = (
    df[df['city'].isin(top5_cities)]
    .groupby(['city', 'role_category'])
    .size()
    .unstack(fill_value=0)
)

plt.figure(figsize=(11, 5))
sns.heatmap(city_role, annot=True, fmt='d', cmap='Blues', linewidths=0.5)
plt.title("Role Category vs Top 5 Cities", fontsize=13, fontweight='bold')
plt.ylabel("")
plt.xlabel("")
plt.tight_layout()
plt.savefig('images/city_role_heatmap.png', dpi=150)
plt.show()

"""### 8. SKILL DEMAND ANALYSIS (from job descriptions)"""

# Define tech skill keywords to search for
SKILLS = {
    'Python':       r'\bpython\b',
    'SQL':          r'\bsql\b',
    'R':            r'\br\b',
    'Excel':        r'\bexcel\b',
    'Tableau':      r'\btableau\b',
    'Power BI':     r'\bpower\s?bi\b',
    'Machine Learning': r'\bmachine\s?learning\b|\bml\b',
    'Deep Learning':r'\bdeep\s?learning\b|\bdl\b',
    'TensorFlow':   r'\btensorflow\b',
    'PyTorch':      r'\bpytorch\b',
    'Spark':        r'\bspark\b|\bpyspark\b',
    'Hadoop':       r'\bhadoop\b',
    'Airflow':      r'\bairflow\b',
    'Docker':       r'\bdocker\b',
    'Git':          r'\bgit\b',
    'AWS':          r'\baws\b|\bamazon\s?web\b',
    'GCP':          r'\bgcp\b|\bgoogle\s?cloud\b',
    'Azure':        r'\bazure\b',
    'Statistics':   r'\bstatistic\b|\bstatistical\b',
    'NLP':          r'\bnlp\b|\bnatural\s?language\b',
}

def count_skill(skill_pattern, text_series):
    mask = text_series.str.contains(skill_pattern, case=False, na=False, regex=True)
    return mask.sum()

desc_series = df['description'].fillna('') + ' ' + df['title'].fillna('')

skill_counts = {
    skill: count_skill(pattern, desc_series)
    for skill, pattern in SKILLS.items()
}

skill_df = (
    pd.DataFrame.from_dict(skill_counts, orient='index', columns=['count'])
    .sort_values('count', ascending=False)
    .reset_index()
    .rename(columns={'index': 'skill'})
)

print("\nSkill Demand (from job descriptions + titles):")
print(skill_df.to_string(index=False))

"""**Plot 7: Skill Demand Bar Chart**"""

plt.figure(figsize=(10, 6))
sns.barplot(data=skill_df, x='count', y='skill',
            hue='skill', palette='Blues_d', legend=False)
plt.title("Most In-Demand Skills in Data Jobs (Indonesia)",
          fontsize=14, fontweight='bold')
plt.xlabel("Number of Job Postings Mentioning Skill")
plt.ylabel("")
plt.tight_layout()
plt.savefig('images/skill_demand.png', dpi=150)
plt.show()

"""**Plot 8: Skills per Role Category**"""

top_skills = ['Python', 'SQL', 'Machine Learning', 'Statistics',
              'Tableau', 'Power BI', 'Excel', 'Deep Learning',
              'AWS', 'Spark']

role_skill_data = []
for role in df['role_category'].unique():
    role_desc = df[df['role_category'] == role]['description'].fillna('') + \
                ' ' + df[df['role_category'] == role]['title'].fillna('')
    for skill in top_skills:
        pattern = SKILLS[skill]
        count = count_skill(pattern, role_desc)
        role_skill_data.append({'role': role, 'skill': skill, 'count': count})

role_skill_df = pd.DataFrame(role_skill_data)
role_skill_pivot = role_skill_df.pivot(index='role', columns='skill', values='count').fillna(0)

plt.figure(figsize=(13, 6))
sns.heatmap(role_skill_pivot, annot=True, fmt='.0f', cmap='Blues', linewidths=0.5)
plt.title("Skill Demand by Role Category", fontsize=13, fontweight='bold')
plt.ylabel("")
plt.xlabel("")
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.savefig('images/skill_by_role.png', dpi=150)
plt.show()

"""**Plot 9: WordCloud from all job descriptions**"""

all_desc = " ".join(desc_series.tolist()).lower()
# remove common stopwords from desc
stopwords_custom = {
    'the', 'and', 'or', 'to', 'a', 'in', 'of', 'for', 'with',
    'is', 'are', 'will', 'be', 'have', 'has', 'you', 'we', 'our',
    'your', 'this', 'that', 'an', 'on', 'at', 'it', 'as', 'by',
    'from', 'not', 'but', 'they', 'all', 'can', 'us', 'about'
}
wc = WordCloud(
    background_color='white',
    width=1000, height=500,
    stopwords=stopwords_custom,
    colormap='Blues',
    max_words=100
).generate(all_desc)

plt.figure(figsize=(12, 6))
plt.imshow(wc)
plt.axis('off')
plt.title("WordCloud — Job Descriptions (Data Roles)", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('images/wordcloud_jobs.png', dpi=150)
plt.show()

"""### 9. CONCLUSION"""

total_jobs     = len(df)
top_role       = df['role_category'].value_counts().idxmax()
top_city       = df[df['city'] != 'Unknown']['city'].value_counts().idxmax()
top_skill      = skill_df.iloc[0]['skill']
top_company    = (
    df[~df['company'].isin(['Private Advertiser', None])]
    ['company'].value_counts().idxmax()
)
remote_pct     = df['is_remote'].mean() * 100
salary_pct     = df['salary'].notna().mean() * 100

# ── Compute additional stats for conclusion ───────────────────────────────────
top2_city      = df[df['city'] != 'Unknown']['city'].value_counts().index[1]
top2_city_n    = df[df['city'] != 'Unknown']['city'].value_counts().iloc[1]
top_city_n     = df[df['city'] != 'Unknown']['city'].value_counts().iloc[0]

# Role counts excluding "Other Data Role"
role_ranked = (
    df[df['role_category'] != 'Other Data Role']['role_category']
    .value_counts()
)
rank1_role, rank1_n = role_ranked.index[0], role_ranked.iloc[0]
rank2_role, rank2_n = role_ranked.index[1], role_ranked.iloc[1]
rank3_role, rank3_n = role_ranked.index[2], role_ranked.iloc[2]

# Top 3 skills
top3_skills = skill_df[skill_df['count'] > 0].head(3)
skill1 = f"{top3_skills.iloc[0]['skill']} ({top3_skills.iloc[0]['count']})"
skill2 = f"{top3_skills.iloc[1]['skill']} ({top3_skills.iloc[1]['count']})"
skill3 = f"{top3_skills.iloc[2]['skill']} ({top3_skills.iloc[2]['count']})"

# Salary not listed pct
salary_not_pct = 100 - salary_pct

print(f"""
► Total jobs scraped    : {total_jobs:,}
► Most in-demand role   : {rank1_role} ({rank1_n} postings)
► Top hiring city       : {top_city} ({top_city_n} postings)
► Most required skill   : {top_skill}
► Top hiring company    : {top_company}
► Remote jobs           : {remote_pct:.1f}%
► Jobs with salary info : {salary_pct:.1f}%

── Key Findings ────────────────────────────────────────────────────

  1. Jakarta is the dominant data job hub
     Jakarta ({top_city_n} jobs) has nearly 3x more postings than
     {top2_city} ({top2_city_n} jobs), confirming it as the primary
     city for data professionals in Indonesia.

  2. Data Engineer is the most in-demand categorized role
     Among clearly categorized roles:
     {rank1_role} ({rank1_n}) > {rank2_role} ({rank2_n}) > {rank3_role} ({rank3_n}).
     Companies are actively building data infrastructure,
     driving high demand for engineering talent.

  3. SQL, Excel, and Python are the top 3 universal skills
     Top skills across all roles: {skill1}, {skill2}, {skill3}.
     SQL and Python appear in almost every role category,
     while Excel remains dominant in Business Analyst/BI roles.

  4. Cloud platforms are increasingly required
     Azure (17) and GCP (14) and AWS (14) appear frequently —
     especially in Data Engineer and ML/AI Engineer roles.
     Cloud skills are becoming a differentiator, not just a bonus.

  5. Machine Learning is concentrated in ML/AI roles
     ML mentions (9 out of 34 ML postings) are in ML/AI Engineer
     roles — confirming that ML is a specialist skill, not a
     general requirement for all data roles.

  6. Salary transparency is very low
     {salary_not_pct:.1f}% of job postings do not list salary.
     Job seekers should use external sources like LinkedIn Salary
     or Glassdoor for compensation benchmarking.

  7. Remote work is non-existent in this dataset
     0% of scraped jobs offer remote work — Indonesia's data job
     market is almost entirely on-site as of scraping date.

── Recommendations for Job Seekers ────────────────────────────────

  🎯 For ALL data roles:
     → Master SQL first — it is required across every role category
     → Python is non-negotiable for DS, DE, and ML/AI roles
     → Target Jakarta — it has {top_city_n} out of {total_jobs} total postings

  📊 For Data Analyst / Business Analyst:
     → Focus on SQL + Excel + Power BI + Tableau
     → These tools dominate BA/BI skill requirements

  ⚙️  For Data Engineer:
     → Learn Python + SQL + AWS/GCP/Azure + Spark/Airflow
     → Cloud and pipeline skills are key differentiators

  🤖 For Data Scientist / ML Engineer:
     → Build strong ML foundations (scikit-learn, ML theory)
     → Add Deep Learning (PyTorch/TensorFlow) for ML/AI track
     → Cloud certification (AWS/GCP) adds significant value

  💼 General advice:
     → Apply to IT consultancies (SIGMATECH, RGF, Nityo Infotech)
       as they hire across multiple clients simultaneously
     → Financial sector (Macquarie, BFI Finance, CIMB Niaga)
       is the most active industry for data hiring
""")